---
- name: Create Social directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
    owner: "{{ user }}"
    group: "{{ group }}"
    recurse: true
  loop:
    - "/mnt/container/tuwunel/db"
    - "/mnt/container/tuwunel/config"
    - "/mnt/container/tuwunel/backups"
    - "/mnt/container/lemmy/config"
    - "/mnt/container/lemmy/pictrs"
    - "/mnt/container/mastodon"

- name: Set up Social
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - src: env/lemmy/settings.env.j2
      dest: "/mnt/container/lemmy/settings.env"
    - src: env/lemmy/config/lemmy.hjson.j2
      dest: "/mnt/container/lemmy/config/lemmy.hjson"
    - src: env/mastodon/settings.env.j2
      dest: "/mnt/container/mastodon/settings.env"
    - src: env/tuwunel/tuwunel.toml.j2
      dest: "/mnt/container/tuwunel/config/tuwunel.toml"
    - src: container/tuwunel/tuwunel_app.container.j2
      dest: "/home/{{ user }}/.config/containers/systemd/tuwunel_app.container"
    - src: container/lemmy/lemmy_app.container.j2
      dest: "/home/{{ user }}/.config/containers/systemd/lemmy_app.container"
    - src: container/lemmy/lemmy_web.container.j2
      dest: "/home/{{ user }}/.config/containers/systemd/lemmy_web.container"
    - src: container/lemmy/lemmy_pictrs.container.j2
      dest: "/home/{{ user }}/.config/containers/systemd/lemmy_pictrs.container"
    - src: container/mastodon/mastodon_sidekiq.container.j2
      dest: "/home/{{ user }}/.config/containers/systemd/mastodon_sidekiq.container"
    - src: container/mastodon/mastodon_web.container.j2
      dest: "/home/{{ user }}/.config/containers/systemd/mastodon_web.container"
    - src: container/mastodon/mastodon_streaming.container.j2
      dest: "/home/{{ user }}/.config/containers/systemd/mastodon_streaming.container"
